### ISSUE TITLE
How can i download it?

### ISSUE THREAD

**Issue by Erkam246** [Virtualoso/ExNihiloPE#3]

**Comment by bia5** [comment]
Click on the 'Code' tab, then click on the 'Clone or Download' button on the mid-top left, then 'Download zip' from the drop down menu.

**Comment by Erkam246** [comment]
But its an src

**Comment by Erkam246** [comment]
I  mean how can i use that

**Comment by TrinityDevelopers** [comment]
He means how to compile.  I would recommend you use an android package compiler like AIDE if you are using a mobile device.

**Comment by Erkam246** [comment]
I am on Windows 10 work this for Windows 10 edition?

**Comment by TheDiamondYT1** [comment]
Nope

**Comment by Erkam246** [comment]
I thinked its an Addon -.-

**Comment by TheDiamondYT1** [comment]
It is an addon

**Comment by Erkam246** [comment]
For MCPE?

**Comment by Erkam246** [comment]
Or for BlockLauncher?

**Comment by TheDiamondYT1** [comment]
BlockLauncher is a Launcher for MCPE, which provides modding capabilities.

**Comment by Erkam246** [comment]
ik but Addon is too for MCPE
